<?php

namespace AppBundle\Repository;

/**
 * ArenaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArenaRepository extends \Doctrine\ORM\EntityRepository
{
}
