<?php

namespace AppBundle\Repository;

/**
 * FightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FightRepository extends \Doctrine\ORM\EntityRepository
{
}
