<?php

namespace AppBundle\Repository;

/**
 * FightStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FightStateRepository extends \Doctrine\ORM\EntityRepository
{
}
