<?php

namespace AppBundle\Repository;

/**
 * NpcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NpcRepository extends \Doctrine\ORM\EntityRepository
{
}
