<?php

namespace AppBundle\Repository;

/**
 * NpcTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NpcTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
