<?php

namespace AppBundle\Repository;

/**
 * PokemonTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokemonTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
