<?php

namespace AppBundle\Repository;

/**
 * PokemonFightStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokemonFightStateRepository extends \Doctrine\ORM\EntityRepository
{
}
