<?php

namespace AppBundle\Repository;

/**
 * PokedexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokedexRepository extends \Doctrine\ORM\EntityRepository
{
}
