# Web site controllers
index:
    path:     /index
    defaults:  { _controller: AppBundle:Index:show }

/inscription:
    type:     annotation
    resource: 'AppBundle\Controller\InscriptionController'

# Rest api controllers
attacktypes:
    type: annotation
    resource: 'AppBundle\RESTController\AttackTypeController'
    defaults: {_format: json}
    prefix:   /api/attacktypes

attack:
    type: annotation
    resource: 'AppBundle\RESTController\AttackController'
    defaults: {_format: json}
    prefix:   /api/attack

pokemon:
    type: annotation
    resource: 'AppBundle\RESTController\PokemonController'
    defaults: {_format: json}
    prefix:   /api/pokemon

trainer:
    type: annotation
    resource: 'AppBundle\RESTController\TrainerController'
    defaults: {_format: json}
    prefix:   /api/trainer

connection:
    type: annotation
    resource: 'AppBundle\RESTController\ConnectionController'
    defaults: {_format: json}
    prefix:   /api/connection

engagement:
    type: annotation
    resource: 'AppBundle\RESTController\MobileEngagementController'
    defaults: {_format: json}
    prefix:   /api/engagement


fight:
    type: annotation
    resource: 'AppBundle\RESTController\FightController'
    defaults: {_format: json}
    prefix:   /api/fight

