attacktypes:
    type: annotation
    resource: "AppBundle\\RESTController\\AttackTypeController"
    defaults: {_format: json}
    prefix:   /api/attacktypes

attack:
    type: annotation
    resource: 'AppBundle\RESTController\AttackController'
    defaults: {_format: json}
    prefix:   /api/attack